ALTER TABLE loyalty_accounts
    ADD COLUMN IF NOT EXISTS streak_days INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS birthday_reward_available BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS cross_cafe_visits INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_brew_date DATE;
